In [77]:
import pandas as pd
import requests
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [111]:
from bs4 import BeautifulSoup

url = 'https://agoravoceaprendeinvestir.com.br/relatorios/listaFII.html'

# headers = {
#     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
# }

# aqui faço a leitura de dados

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table')

# pandas read_html function returns a list of DataFrame objects, even if there is only a single table contained in the HTML content.
# So, you must pick out the DataFrame you want from the returned list.
df = pd.read_html(str(table), decimal=',', thousands='.')[0]

# print(df)
df.columns = ['Código do fundo', 'Setor', 'Preço Atual', 'Liquidez Diária', 'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado', 'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média', 'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada', 'PatrimônioLíq.', 'VPA', 'P/VPA', 'DY Patrimonial', 'Variação Patrimonial', 'Rentab. Patr. no Período', 'Rentab. Patr. Acumulada', 'VacânciaFísica', 'VacânciaFinanceira', 'Quantidade Ativos']

In [85]:
df.head()

  Código do fundo                 Setor Preço Atual  Liquidez Diária Dividendo DividendYield DY (3M)Acumulado DY (6M)Acumulado DY (12M)Acumulado DY (3M)Média DY (6M)Média DY (12M)Média DY Ano Variação Preço Rentab.Período Rentab.Acumulada     PatrimônioLíq.          VPA  P/VPA DY Patrimonial Variação Patrimonial Rentab. Patr. no Período Rentab. Patr. Acumulada VacânciaFísica VacânciaFinanceira  Quantidade Ativos
0          FIVN11             Shoppings     R$ 3,09         492650.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%    NaN          0,00%          0,00%            0,00%   R$ 72.278.389,33      R$ 7,68   0.40            NaN                  NaN                      NaN                     NaN         56,00%                NaN                  1
1          BZLI11  TÃ­tulos e Val. Mob.    R$ 17,11             30.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          0,68%          0,68%            1,14%  R$ 448.259.394,13     R$ 10,71   1.60            NaN                  NaN                      NaN                     NaN            NaN                NaN                  0
2          XTED11    Lajes Corporativas     R$ 8,82          22230.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          1,10%          1,10%          -37,83%   R$ 27.688.895,17     R$ 13,26   0.67            NaN                  NaN                      NaN                     NaN          0,00%            100,00%                  1
3          ALMI11    Lajes Corporativas   R$ 765,00            200.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          2,27%          2,27%          -28,29%  R$ 224.901.265,10  R$ 2.022,91   0.38            NaN                  NaN                      NaN                     NaN         64,05%                NaN                  1
4          PABY11              HÃ­brido    R$ 12,09            410.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%        -19,84%        -19,84%          -31,62%  R$ -13.244.892,55    R$ -17,46  -0.69            NaN                  NaN                      NaN                     NaN            NaN                NaN                  1

In [90]:
df.head()

  Código do fundo                 Setor Preço Atual  Liquidez Diária Dividendo DividendYield DY (3M)Acumulado DY (6M)Acumulado DY (12M)Acumulado DY (3M)Média DY (6M)Média DY (12M)Média DY Ano Variação Preço Rentab.Período Rentab.Acumulada     PatrimônioLíq.          VPA  P/VPA DY Patrimonial Variação Patrimonial Rentab. Patr. no Período Rentab. Patr. Acumulada VacânciaFísica VacânciaFinanceira  Quantidade Ativos
0          FIVN11             Shoppings     R$ 3,09         492650.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%    NaN          0,00%          0,00%            0,00%   R$ 72.278.389,33      R$ 7,68   0.40            NaN                  NaN                      NaN                     NaN         56,00%                NaN                  1
1          BZLI11  TÃ­tulos e Val. Mob.    R$ 17,11             30.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          0,68%          0,68%            1,14%  R$ 448.259.394,13     R$ 10,71   1.60            NaN                  NaN                      NaN                     NaN            NaN                NaN                  0
2          XTED11    Lajes Corporativas     R$ 8,82          22230.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          1,10%          1,10%          -37,83%   R$ 27.688.895,17     R$ 13,26   0.67            NaN                  NaN                      NaN                     NaN          0,00%            100,00%                  1
3          ALMI11    Lajes Corporativas   R$ 765,00            200.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%          2,27%          2,27%          -28,29%  R$ 224.901.265,10  R$ 2.022,91   0.38            NaN                  NaN                      NaN                     NaN         64,05%                NaN                  1
4          PABY11              HÃ­brido    R$ 12,09            410.0   R$ 0,00         0,00%            0,00%            0,00%             0,00%        0,00%        0,00%         0,00%  0,00%        -19,84%        -19,84%          -31,62%  R$ -13.244.892,55    R$ -17,46  -0.69            NaN                  NaN                      NaN                     NaN            NaN                NaN                  1

In [104]:
# df['Preço Atual'].str.replace('R$ ', '',regex=False).str.replace(r'\.','', regex=True).str.replace(',','.')

In [112]:

# Remove "R$" from "Preço Atual", "Dividendo", "PatrimônioLíq." and "VPA" columns and convert to float
df.loc[:,'Preço Atual'] = df['Preço Atual'].str.replace('R$ ', '',regex=False).str.replace(r'\.','', regex=True).str.replace(',','.').astype(float)
df.loc[:,'Dividendo'] = df['Dividendo'].str.replace('R$ ', '',regex=False).str.replace(r'\.','', regex=True).str.replace(',','.').astype(float)
df.loc[:,'PatrimônioLíq.'] = df['PatrimônioLíq.'].str.replace('R$ ', '',regex=False).str.replace(r'\.','', regex=True).str.replace(',','.').astype(float)
df.loc[:,'VPA'] = df['VPA'].str.replace('R$ ', '',regex=False).str.replace(r'\.','', regex=True).str.replace(',','.').astype(float)

# Remove "%" from percentage columns and convert to float
percentage_columns = ['DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado', 'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média', 'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira']
for column in percentage_columns:
    df[column] = df[column].str.replace('%', '').str.replace(',', '.').astype(float)

# Fill NaN values with a specific value (e.g., 0)
df.fillna(0, inplace=True)

In [113]:
df.head()

  Código do fundo                 Setor  Preço Atual  Liquidez Diária  Dividendo  DividendYield  DY (3M)Acumulado  DY (6M)Acumulado  DY (12M)Acumulado  DY (3M)Média  DY (6M)Média  DY (12M)Média  DY Ano  Variação Preço  Rentab.Período  Rentab.Acumulada  PatrimônioLíq.      VPA  P/VPA DY Patrimonial Variação Patrimonial Rentab. Patr. no Período Rentab. Patr. Acumulada  VacânciaFísica  VacânciaFinanceira  Quantidade Ativos
0          FIVN11             Shoppings         3.09         492650.0        0.0            0.0               0.0               0.0                0.0           0.0           0.0            0.0     0.0            0.00            0.00              0.00    7.227839e+07     7.68   0.40              0                    0                        0                       0           56.00                 0.0                  1
1          BZLI11  TÃ­tulos e Val. Mob.        17.11             30.0        0.0            0.0               0.0               0.0                0.0           0.0           0.0            0.0     0.0            0.68            0.68              1.14    4.482594e+08    10.71   1.60              0                    0                        0                       0            0.00                 0.0                  0
2          XTED11    Lajes Corporativas         8.82          22230.0        0.0            0.0               0.0               0.0                0.0           0.0           0.0            0.0     0.0            1.10            1.10            -37.83    2.768890e+07    13.26   0.67              0                    0                        0                       0            0.00               100.0                  1
3          ALMI11    Lajes Corporativas       765.00            200.0        0.0            0.0               0.0               0.0                0.0           0.0           0.0            0.0     0.0            2.27            2.27            -28.29    2.249013e+08  2022.91   0.38              0                    0                        0                       0           64.05                 0.0                  1
4          PABY11              HÃ­brido        12.09            410.0        0.0            0.0               0.0               0.0                0.0           0.0           0.0            0.0     0.0          -19.84          -19.84            -31.62   -1.324489e+07   -17.46  -0.69              0                    0                        0                       0            0.00                 0.0                  1

In [38]:
df.to_excel('Fundos_imobiliarios.xlsx')

In [49]:
df_lupa = pd.read_excel("DB de para FII.xlsx",decimal =',', thousands='.')

In [57]:
df_lupa['Ticker'].duplicated().sum()

1

In [58]:
df_lupa[df_lupa['Ticker'].duplicated()]

    Ticker           Público Alvo                              Tipo de Fii                                      Administrador  Último Rend. (R$)  Último Rend. (%)       Data Pagamento   Data Base  Rend. Méd. 12m (R$)  Rend. Méd. 12m (%)  Patrimônio/Cota  Cotação/VP  N° negócios/mês  Partic. IFIX  Número Cotistas    Patrimônio  Cota base
50  VERE11  Investidores em Geral  Tijolo:Imóveis Industriais e Logísticos  VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...               4.76               NaN  2023-10-07 00:00:00  30/06/2023                 2.35                 NaN           367.09        0.64              NaN           NaN             53.0  2.077464e+08        NaN

In [59]:
df_lupa[df_lupa['Ticker']=='VERE11']

    Ticker           Público Alvo                              Tipo de Fii                                      Administrador  Último Rend. (R$)  Último Rend. (%)       Data Pagamento   Data Base  Rend. Méd. 12m (R$)  Rend. Méd. 12m (%)  Patrimônio/Cota  Cotação/VP  N° negócios/mês  Partic. IFIX  Número Cotistas    Patrimônio  Cota base
49  VERE11  Investidores em Geral  Tijolo:Imóveis Industriais e Logísticos  VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...               2.07               NaN  2023-07-07 00:00:00  30/06/2023                 2.35                 NaN           367.09        0.64              NaN           NaN             53.0  2.077464e+08        NaN
50  VERE11  Investidores em Geral  Tijolo:Imóveis Industriais e Logísticos  VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...               4.76               NaN  2023-10-07 00:00:00  30/06/2023                 2.35                 NaN           367.09        0.64              NaN           NaN             53.0  2.077464e+08        NaN

In [75]:
df_lupa['Ticker'].nunique()

522

In [65]:
len(set(df_lupa['Ticker'].tolist()) - set(df['Código do fundo'].tolist()))

215

In [70]:
df_lupa.merge(df, how='inner', left_on='Ticker', right_on='Código do fundo').head(2)

   Ticker           Público Alvo             Tipo de Fii                                      Administrador  Último Rend. (R$)  Último Rend. (%) Data Pagamento   Data Base  Rend. Méd. 12m (R$)  Rend. Méd. 12m (%)  Patrimônio/Cota  Cotação/VP  N° negócios/mês  Partic. IFIX  Número Cotistas   Patrimônio  Cota base Código do fundo               Setor  Preço Atual  Liquidez Diária  Dividendo  DividendYield  DY (3M)Acumulado  DY (6M)Acumulado  DY (12M)Acumulado  DY (3M)Média  DY (6M)Média  DY (12M)Média  DY Ano  Variação Preço  Rentab.Período  Rentab.Acumulada  PatrimônioLíq.     VPA  P/VPA DY Patrimonial Variação Patrimonial Rentab. Patr. no Período Rentab. Patr. Acumulada  VacânciaFísica  VacânciaFinanceira  Quantidade Ativos
0  ZAVI11  Investidores em Geral  Fundo Misto:Indefinido  VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...               1.16              0.92     14/07/2023  30/06/2023                 0.84                0.66           127.39        0.92              2.0           NaN            2.473  127018551.3     126.67          ZAVI11            HÃ­brido       126.00          31100.0        1.1           0.87              1.75               0.0                0.0          0.58           0.0            0.0    1.75             0.0            0.87              1.75    1.183398e+08  127.73   0.99          0,86%                0,33%                    1,20%                   3,70%             0.0                 0.0                  0
1  XTED11                    NaN                     NaN                                                NaN                NaN               NaN            NaN         NaN                  NaN                 NaN              NaN         NaN              NaN           NaN              NaN          NaN        NaN          XTED11  Lajes Corporativas         8.82          22230.0        0.0           0.00              0.00               0.0                0.0          0.00           0.0            0.0    0.00             1.1            1.10            -37.83    2.768890e+07   13.26   0.67              0                    0                        0                       0             0.0               100.0                  1

In [71]:
df_lupa.head(2)

   Ticker           Público Alvo                           Tipo de Fii                                      Administrador  Último Rend. (R$)  Último Rend. (%) Data Pagamento   Data Base  Rend. Méd. 12m (R$)  Rend. Méd. 12m (%)  Patrimônio/Cota  Cotação/VP  N° negócios/mês  Partic. IFIX  Número Cotistas    Patrimônio  Cota base
0  ZIFI11  Investidores em Geral  Fundo Misto:Fundo de Desenvolvimento  PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VAL...               3.31               NaN     14/07/2022  30/06/2022                 0.68                 NaN          1200.00        0.83             40.0           NaN           64.000  5.730751e+07        NaN
1  ZAVI11  Investidores em Geral                Fundo Misto:Indefinido  VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...               1.16              0.92     14/07/2023  30/06/2023                 0.84                0.66           127.39        0.92              2.0           NaN            2.473  1.270186e+08     126.67

In [73]:
df_lupa['Tipo de Fii'].unique()

array(['Fundo Misto:Fundo de Desenvolvimento', 'Fundo Misto:Indefinido',
       nan, 'Papel:Fundo de Fundos', 'Tijolo:Shoppings',
       'Tijolo:Imóveis Industriais e Logísticos', 'Tijolo:Hotéis',
       'Tijolo:Lajes Corporativas', 'Papel:Papéis', 'Fiagro:Fiagro',
       'Fundo Misto:Misto', 'Sem categoria:',
       'Tijolo:Imóveis Residenciais',
       'Tijolo:Imóveis Comerciais - Outros', 'Fundo Misto:Papéis',
       'Outros:Indefinido', 'Tijolo:', 'Fundo Misto:', 'Tijolo:Varejo',
       'Tijolo:Educacional', 'Tijolo:Hospitalar',
       'Tijolo:Fundo de Desenvolvimento', 'Fiagro:',
       'Tijolo:Agências de Bancos', 'Papel:'], dtype=object)

In [72]:
df_lupa['Público Alvo']==

0        Investidores em Geral
1        Investidores em Geral
2      Investidor Profissional
3                          NaN
4                          NaN
                ...
518      Investidores em Geral
519                        NaN
520      Investidores em Geral
521      Investidores em Geral
522                        NaN
Name: Público Alvo, Length: 523, dtype: object